//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace commander.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_script
    {
        public int id { get; set; }
        public int id_project { get; set; }
        public int order { get; set; }
        public string name { get; set; }
        public string script { get; set; }
        public Nullable<System.DateTime> last_executed { get; set; }
        public System.DateTime cd { get; set; }
    
        public virtual project project { get; set; }
    }
}
